// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_gardienbit.DAL;

#nullable disable

namespace api_gardienbit.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_gardienbit.Models.Category", b =>
                {
                    b.Property<Guid>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CatEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CatVaultVauId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CatId");

                    b.HasIndex("CatVaultVauId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("api_gardienbit.Models.Client", b =>
                {
                    b.Property<Guid>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CliEntraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CliName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CliId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("api_gardienbit.Models.Log", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LogActionLoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogCliEntraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogCliId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogPwpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogPwpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogVauId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogVauName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("LogActionLoaId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("api_gardienbit.Models.LogAction", b =>
                {
                    b.Property<Guid>("LoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaId");

                    b.ToTable("LogActions");
                });

            modelBuilder.Entity("api_gardienbit.Models.PwdPackage", b =>
                {
                    b.Property<Guid>("PwpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PwPVaultVauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PwpCategoryCatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PwpEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PwpLastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PwpId");

                    b.HasIndex("PwPVaultVauId");

                    b.HasIndex("PwpCategoryCatId");

                    b.ToTable("PwdPackages");
                });

            modelBuilder.Entity("api_gardienbit.Models.Vault", b =>
                {
                    b.Property<Guid>("VauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VauClientCliId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VauEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VauFavorite")
                        .HasColumnType("bit");

                    b.Property<byte[]>("VauHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("VauLastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VauName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("VauSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("VauTOTP")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("VauId");

                    b.HasIndex("VauClientCliId");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultSession", b =>
                {
                    b.Property<Guid>("VasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VasClientCliId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("VasEncryptionKeyPrivate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("VasEncryptionKeyPublic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("VasEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VasIsTotpResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VasLastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("VasPrivateKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("VasPublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("VasVaultVauId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VasId");

                    b.HasIndex("VasClientCliId");

                    b.HasIndex("VasVaultVauId");

                    b.ToTable("VaultSessions");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultUserAccess", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsUsed")
                        .HasColumnType("int");

                    b.Property<int>("NbUsed")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaultId", "UserId");

                    b.ToTable("VaultUserAccess");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultUserLink", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccessGrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VaultId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("VaultUserLinks");
                });

            modelBuilder.Entity("api_gardienbit.Models.Category", b =>
                {
                    b.HasOne("api_gardienbit.Models.Vault", "CatVault")
                        .WithMany("VauCategories")
                        .HasForeignKey("CatVaultVauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatVault");
                });

            modelBuilder.Entity("api_gardienbit.Models.Log", b =>
                {
                    b.HasOne("api_gardienbit.Models.LogAction", "LogAction")
                        .WithMany("Logs")
                        .HasForeignKey("LogActionLoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogAction");
                });

            modelBuilder.Entity("api_gardienbit.Models.PwdPackage", b =>
                {
                    b.HasOne("api_gardienbit.Models.Vault", "PwPVault")
                        .WithMany("VauPwdPackages")
                        .HasForeignKey("PwPVaultVauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_gardienbit.Models.Category", "PwpCategory")
                        .WithMany("CatPwdPackages")
                        .HasForeignKey("PwpCategoryCatId");

                    b.OwnsOne("api_gardienbit.Models.EncryptedField", "PwpCom", b1 =>
                        {
                            b1.Property<Guid>("PwdPackagePwpId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("EnfAuthTag")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfCipherText")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfInitialisationVector")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.HasKey("PwdPackagePwpId");

                            b1.ToTable("PwdPackages");

                            b1.WithOwner()
                                .HasForeignKey("PwdPackagePwpId");
                        });

                    b.OwnsOne("api_gardienbit.Models.EncryptedField", "PwpContent", b1 =>
                        {
                            b1.Property<Guid>("PwdPackagePwpId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("EnfAuthTag")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfCipherText")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfInitialisationVector")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.HasKey("PwdPackagePwpId");

                            b1.ToTable("PwdPackages");

                            b1.WithOwner()
                                .HasForeignKey("PwdPackagePwpId");
                        });

                    b.OwnsOne("api_gardienbit.Models.EncryptedField", "PwpName", b1 =>
                        {
                            b1.Property<Guid>("PwdPackagePwpId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("EnfAuthTag")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfCipherText")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfInitialisationVector")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.HasKey("PwdPackagePwpId");

                            b1.ToTable("PwdPackages");

                            b1.WithOwner()
                                .HasForeignKey("PwdPackagePwpId");
                        });

                    b.OwnsOne("api_gardienbit.Models.EncryptedField", "PwpUrl", b1 =>
                        {
                            b1.Property<Guid>("PwdPackagePwpId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("EnfAuthTag")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfCipherText")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<byte[]>("EnfInitialisationVector")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.HasKey("PwdPackagePwpId");

                            b1.ToTable("PwdPackages");

                            b1.WithOwner()
                                .HasForeignKey("PwdPackagePwpId");
                        });

                    b.Navigation("PwPVault");

                    b.Navigation("PwpCategory");

                    b.Navigation("PwpCom")
                        .IsRequired();

                    b.Navigation("PwpContent")
                        .IsRequired();

                    b.Navigation("PwpName")
                        .IsRequired();

                    b.Navigation("PwpUrl")
                        .IsRequired();
                });

            modelBuilder.Entity("api_gardienbit.Models.Vault", b =>
                {
                    b.HasOne("api_gardienbit.Models.Client", "VauClient")
                        .WithMany("CliVaults")
                        .HasForeignKey("VauClientCliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VauClient");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultSession", b =>
                {
                    b.HasOne("api_gardienbit.Models.Client", "VasClient")
                        .WithMany("CliSessions")
                        .HasForeignKey("VasClientCliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api_gardienbit.Models.Vault", "VasVault")
                        .WithMany("VauSessions")
                        .HasForeignKey("VasVaultVauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VasClient");

                    b.Navigation("VasVault");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultUserAccess", b =>
                {
                    b.HasOne("api_gardienbit.Models.Vault", "Vault")
                        .WithMany("SharedWithUsers")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("api_gardienbit.Models.VaultUserLink", b =>
                {
                    b.HasOne("api_gardienbit.Models.Client", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_gardienbit.Models.Vault", "Vault")
                        .WithMany("VaultUserLinks")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("api_gardienbit.Models.Category", b =>
                {
                    b.Navigation("CatPwdPackages");
                });

            modelBuilder.Entity("api_gardienbit.Models.Client", b =>
                {
                    b.Navigation("CliSessions");

                    b.Navigation("CliVaults");
                });

            modelBuilder.Entity("api_gardienbit.Models.LogAction", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("api_gardienbit.Models.Vault", b =>
                {
                    b.Navigation("SharedWithUsers");

                    b.Navigation("VauCategories");

                    b.Navigation("VauPwdPackages");

                    b.Navigation("VauSessions");

                    b.Navigation("VaultUserLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
